import type { Config } from 'tailwindcss';

/**
 * Tailwind CSS Configuration
 *
 * Theme values are generated from design tokens (src/design-system/tokens.ts).
 * Run `npm run generate:tokens` to regenerate after token changes.
 */
const config: Config = {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        primary: {
          50: 'var(--color-primary-50)',
          100: 'var(--color-primary-100)',
          200: 'var(--color-primary-200)',
          300: 'var(--color-primary-300)',
          400: 'var(--color-primary-400)',
          500: 'var(--color-primary-500)',
          600: 'var(--color-primary-600)',
          700: 'var(--color-primary-700)',
          800: 'var(--color-primary-800)',
          900: 'var(--color-primary-900)',
          DEFAULT: 'var(--color-primary-500)',
        },
        secondary: {
          50: 'var(--color-secondary-50)',
          100: 'var(--color-secondary-100)',
          200: 'var(--color-secondary-200)',
          300: 'var(--color-secondary-300)',
          400: 'var(--color-secondary-400)',
          500: 'var(--color-secondary-500)',
          600: 'var(--color-secondary-600)',
          700: 'var(--color-secondary-700)',
          800: 'var(--color-secondary-800)',
          900: 'var(--color-secondary-900)',
          DEFAULT: 'var(--color-secondary-500)',
        },
        accent: {
          50: 'var(--color-accent-50)',
          100: 'var(--color-accent-100)',
          200: 'var(--color-accent-200)',
          300: 'var(--color-accent-300)',
          400: 'var(--color-accent-400)',
          500: 'var(--color-accent-500)',
          600: 'var(--color-accent-600)',
          700: 'var(--color-accent-700)',
          800: 'var(--color-accent-800)',
          900: 'var(--color-accent-900)',
          DEFAULT: 'var(--color-accent-500)',
        },
        success: {
          50: 'var(--color-success-50)',
          100: 'var(--color-success-100)',
          200: 'var(--color-success-200)',
          300: 'var(--color-success-300)',
          400: 'var(--color-success-400)',
          500: 'var(--color-success-500)',
          600: 'var(--color-success-600)',
          700: 'var(--color-success-700)',
          800: 'var(--color-success-800)',
          900: 'var(--color-success-900)',
          DEFAULT: 'var(--color-success-500)',
        },
        error: {
          50: 'var(--color-error-50)',
          100: 'var(--color-error-100)',
          200: 'var(--color-error-200)',
          300: 'var(--color-error-300)',
          400: 'var(--color-error-400)',
          500: 'var(--color-error-500)',
          600: 'var(--color-error-600)',
          700: 'var(--color-error-700)',
          800: 'var(--color-error-800)',
          900: 'var(--color-error-900)',
          DEFAULT: 'var(--color-error-500)',
        },
        background: {
          light: 'var(--color-background)',
          dark: 'var(--color-background)',
          DEFAULT: 'var(--color-background)',
        },
        text: {
          light: 'var(--color-text)',
          muted: 'var(--color-text-muted)',
          dark: 'var(--color-text)',
          DEFAULT: 'var(--color-text)',
        },
      },
      spacing: {
        '0': 'var(--spacing-0, 0px)',
        '1': 'var(--spacing-1, 0.25rem)',
        '2': 'var(--spacing-2, 0.5rem)',
        '3': 'var(--spacing-3, 0.75rem)',
        '4': 'var(--spacing-4, 1rem)',
        '5': 'var(--spacing-5, 1.25rem)',
        '6': 'var(--spacing-6, 1.5rem)',
        '8': 'var(--spacing-8, 2rem)',
        '10': 'var(--spacing-10, 2.5rem)',
        '12': 'var(--spacing-12, 3rem)',
        '16': 'var(--spacing-16, 4rem)',
        '20': 'var(--spacing-20, 5rem)',
        '24': 'var(--spacing-24, 6rem)',
      },
      fontFamily: {
        sans: [
          'Inter',
          'ui-sans-serif',
          'system-ui',
          '-apple-system',
          'BlinkMacSystemFont',
          'Segoe UI',
          'Roboto',
          'Helvetica Neue',
          'Arial',
          'sans-serif',
        ],
        mono: [
          'JetBrains Mono',
          'ui-monospace',
          'SFMono-Regular',
          'Menlo',
          'Monaco',
          'Consolas',
          'Liberation Mono',
          'Courier New',
          'monospace',
        ],
      },
      fontSize: {
        xs: ['var(--font-size-xs, 0.75rem)', { lineHeight: 'var(--line-height-xs, 1rem)' }],
        sm: ['var(--font-size-sm, 0.875rem)', { lineHeight: 'var(--line-height-sm, 1.25rem)' }],
        base: ['var(--font-size-base, 1rem)', { lineHeight: 'var(--line-height-base, 1.5rem)' }],
        lg: ['var(--font-size-lg, 1.125rem)', { lineHeight: 'var(--line-height-lg, 1.75rem)' }],
        xl: ['var(--font-size-xl, 1.25rem)', { lineHeight: 'var(--line-height-xl, 1.75rem)' }],
        '2xl': ['var(--font-size-2xl, 1.5rem)', { lineHeight: 'var(--line-height-2xl, 2rem)' }],
        '3xl': [
          'var(--font-size-3xl, 1.875rem)',
          { lineHeight: 'var(--line-height-3xl, 2.25rem)' },
        ],
        '4xl': ['var(--font-size-4xl, 2.25rem)', { lineHeight: 'var(--line-height-4xl, 2.5rem)' }],
        '5xl': ['var(--font-size-5xl, 3rem)', { lineHeight: 'var(--line-height-5xl, 1)' }],
      },
      borderRadius: {
        sm: 'var(--radius-sm, 4px)',
        md: 'var(--radius-md, 8px)',
        lg: 'var(--radius-lg, 12px)',
        xl: 'var(--radius-xl, 16px)',
        full: 'var(--radius-full, 9999px)',
      },
      boxShadow: {
        'level-0': 'none',
        'level-1': 'var(--shadow-level-1)',
        'level-2': 'var(--shadow-level-2)',
        'level-3': 'var(--shadow-level-3)',
        'level-4': 'var(--shadow-level-4)',
      },
      borderWidth: {
        thin: 'var(--border-thin, 1px)',
        medium: 'var(--border-medium, 1.5px)',
        thick: 'var(--border-thick, 2px)',
      },
      transitionDuration: {
        instant: 'var(--duration-instant, 50ms)',
        fast: 'var(--duration-fast, 100ms)',
        normal: 'var(--duration-normal, 150ms)',
        moderate: 'var(--duration-moderate, 200ms)',
        slow: 'var(--duration-slow, 300ms)',
      },
      transitionTimingFunction: {
        'ease-out': 'var(--ease-out, cubic-bezier(0.33, 1, 0.68, 1))',
        'ease-in': 'var(--ease-in, cubic-bezier(0.32, 0, 0.67, 0))',
        'ease-in-out': 'var(--ease-in-out, cubic-bezier(0.65, 0, 0.35, 1))',
      },
      screens: {
        sm: '640px',
        md: '768px',
        lg: '1024px',
        xl: '1280px',
      },
      keyframes: {
        indeterminate: {
          '0%': { transform: 'translateX(-100%)' },
          '100%': { transform: 'translateX(400%)' },
        },
        'slide-up': {
          '0%': { transform: 'translateY(100%)' },
          '100%': { transform: 'translateY(0)' },
        },
        shimmer: {
          '0%': { transform: 'translateX(-100%)' },
          '100%': { transform: 'translateX(100%)' },
        },
        'page-enter': {
          '0%': { opacity: '0', transform: 'translateY(8px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        'celebration-enter': {
          '0%': { opacity: '0', transform: 'translateX(-50%) scale(0.8)' },
          '100%': { opacity: '1', transform: 'translateX(-50%) scale(1)' },
        },
      },
      animation: {
        indeterminate: 'indeterminate 1.5s ease-in-out infinite',
        'slide-up': 'slide-up 200ms ease',
        shimmer: 'shimmer 1.5s ease-in-out infinite',
        'page-enter': 'page-enter 200ms ease-out forwards',
        'celebration-enter': 'celebration-enter 200ms ease-out forwards',
      },
    },
  },
  plugins: [],
};

export default config;
