import type { CanvasTemplate } from '../types';

export const invoiceTemplate: CanvasTemplate = {
  id: 'template-invoice',
  name: 'Invoice',
  category: 'invoice',
  thumbnail:
    'data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMTIwIiBoZWlnaHQ9IjE2MCIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cmVjdCB3aWR0aD0iMTIwIiBoZWlnaHQ9IjE2MCIgZmlsbD0iI2ZmZiIgc3Ryb2tlPSIjZTVlN2ViIiBzdHJva2Utd2lkdGg9IjEiLz48cmVjdCB4PSIxMCIgeT0iMTAiIHdpZHRoPSI0MCIgaGVpZ2h0PSIxNSIgZmlsbD0iIzM0OTlmZiIgcng9IjIiLz48cmVjdCB4PSIxMCIgeT0iMzUiIHdpZHRoPSI2MCIgaGVpZ2h0PSI0IiBmaWxsPSIjZTVlN2ViIi8+PHJlY3QgeD0iMTAiIHk9IjQ1IiB3aWR0aD0iNDAiIGhlaWdodD0iNCIgZmlsbD0iI2U1ZTdlYiIvPjxyZWN0IHg9IjEwIiB5PSI2NSIgd2lkdGg9IjEwMCIgaGVpZ2h0PSIxIiBmaWxsPSIjZDFkNWRiIi8+PHJlY3QgeD0iMTAiIHk9Ijc1IiB3aWR0aD0iMTAwIiBoZWlnaHQ9IjQiIGZpbGw9IiNmM2Y0ZjYiLz48cmVjdCB4PSIxMCIgeT0iODUiIHdpZHRoPSIxMDAiIGhlaWdodD0iNCIgZmlsbD0iI2YzZjRmNiIvPjxyZWN0IHg9IjEwIiB5PSI5NSIgd2lkdGg9IjEwMCIgaGVpZ2h0PSI0IiBmaWxsPSIjZjNmNGY2Ii8+PHJlY3QgeD0iNzAiIHk9IjEyMCIgd2lkdGg9IjQwIiBoZWlnaHQ9IjEwIiBmaWxsPSIjMzQ5OWZmIiByeD0iMiIvPjwvc3ZnPg==',
  pages: [
    {
      id: 'invoice-page-1',
      width: 210,
      height: 297,
      backgroundColor: '#FFFFFF',
      elements: [
        {
          id: 'inv-header-bg',
          type: 'shape',
          shapeType: 'rectangle',
          x: 0,
          y: 0,
          width: 210,
          height: 50,
          rotation: 0,
          opacity: 100,
          zIndex: 0,
          locked: false,
          visible: true,
          fill: '#2563eb',
          stroke: 'transparent',
          strokeWidth: 0,
          borderStyle: 'solid',
        },
        {
          id: 'inv-title',
          type: 'text',
          x: 15,
          y: 15,
          width: 100,
          height: 20,
          rotation: 0,
          opacity: 100,
          zIndex: 1,
          locked: false,
          visible: true,
          content: 'INVOICE',
          fontFamily: 'Inter, sans-serif',
          fontSize: 28,
          fontColor: '#FFFFFF',
          bold: true,
          italic: false,
          underline: false,
          alignment: 'left',
        },
        {
          id: 'inv-number',
          type: 'text',
          x: 130,
          y: 18,
          width: 65,
          height: 12,
          rotation: 0,
          opacity: 100,
          zIndex: 2,
          locked: false,
          visible: true,
          content: '#INV-001',
          fontFamily: 'Inter, sans-serif',
          fontSize: 14,
          fontColor: '#FFFFFF',
          bold: false,
          italic: false,
          underline: false,
          alignment: 'right',
        },
        {
          id: 'inv-from-label',
          type: 'text',
          x: 15,
          y: 65,
          width: 80,
          height: 8,
          rotation: 0,
          opacity: 100,
          zIndex: 3,
          locked: false,
          visible: true,
          content: 'From:',
          fontFamily: 'Inter, sans-serif',
          fontSize: 10,
          fontColor: '#6b7280',
          bold: true,
          italic: false,
          underline: false,
          alignment: 'left',
        },
        {
          id: 'inv-from-name',
          type: 'text',
          x: 15,
          y: 75,
          width: 80,
          height: 20,
          rotation: 0,
          opacity: 100,
          zIndex: 4,
          locked: false,
          visible: true,
          content: 'Your Company Name\n123 Business St\nCity, State 12345',
          fontFamily: 'Inter, sans-serif',
          fontSize: 10,
          fontColor: '#374151',
          bold: false,
          italic: false,
          underline: false,
          alignment: 'left',
        },
        {
          id: 'inv-to-label',
          type: 'text',
          x: 120,
          y: 65,
          width: 80,
          height: 8,
          rotation: 0,
          opacity: 100,
          zIndex: 5,
          locked: false,
          visible: true,
          content: 'Bill To:',
          fontFamily: 'Inter, sans-serif',
          fontSize: 10,
          fontColor: '#6b7280',
          bold: true,
          italic: false,
          underline: false,
          alignment: 'left',
        },
        {
          id: 'inv-to-name',
          type: 'text',
          x: 120,
          y: 75,
          width: 80,
          height: 20,
          rotation: 0,
          opacity: 100,
          zIndex: 6,
          locked: false,
          visible: true,
          content: 'Client Name\n456 Client Ave\nCity, State 67890',
          fontFamily: 'Inter, sans-serif',
          fontSize: 10,
          fontColor: '#374151',
          bold: false,
          italic: false,
          underline: false,
          alignment: 'left',
        },
        {
          id: 'inv-table-header',
          type: 'shape',
          shapeType: 'rectangle',
          x: 15,
          y: 120,
          width: 180,
          height: 10,
          rotation: 0,
          opacity: 100,
          zIndex: 7,
          locked: false,
          visible: true,
          fill: '#f3f4f6',
          stroke: '#e5e7eb',
          strokeWidth: 1,
          borderStyle: 'solid',
        },
        {
          id: 'inv-total-label',
          type: 'text',
          x: 120,
          y: 220,
          width: 40,
          height: 10,
          rotation: 0,
          opacity: 100,
          zIndex: 8,
          locked: false,
          visible: true,
          content: 'Total:',
          fontFamily: 'Inter, sans-serif',
          fontSize: 14,
          fontColor: '#111827',
          bold: true,
          italic: false,
          underline: false,
          alignment: 'right',
        },
        {
          id: 'inv-total-amount',
          type: 'text',
          x: 165,
          y: 220,
          width: 30,
          height: 10,
          rotation: 0,
          opacity: 100,
          zIndex: 9,
          locked: false,
          visible: true,
          content: '$0.00',
          fontFamily: 'Inter, sans-serif',
          fontSize: 14,
          fontColor: '#2563eb',
          bold: true,
          italic: false,
          underline: false,
          alignment: 'right',
        },
      ],
    },
  ],
};
