import type { CanvasTemplate } from '../types';

/**
 * Classic Corporate Letterhead — Law firm / financial services style.
 * Bold navy company name top-left, thin separator line, centered contact bar,
 * body text, and signature at bottom.
 */
export const letterheadClassicTemplate: CanvasTemplate = {
  id: 'template-letterhead-classic',
  name: 'Classic Corporate Letterhead',
  category: 'letterhead',
  thumbnail:
    'data:image/svg+xml;base64,' +
    btoa(
      '<svg width="120" height="160" xmlns="http://www.w3.org/2000/svg">' +
        '<rect width="120" height="160" fill="#fff" stroke="#e5e7eb" stroke-width="1"/>' +
        '<rect x="10" y="12" width="55" height="7" fill="#1a2332"/>' +
        '<rect x="10" y="24" width="100" height="1" fill="#1a2332"/>' +
        '<rect x="30" y="29" width="60" height="3" fill="#d1d5db"/>' +
        '<rect x="10" y="45" width="100" height="3" fill="#e5e7eb"/>' +
        '<rect x="10" y="53" width="100" height="3" fill="#e5e7eb"/>' +
        '<rect x="10" y="61" width="90" height="3" fill="#e5e7eb"/>' +
        '<rect x="10" y="69" width="100" height="3" fill="#e5e7eb"/>' +
        '<rect x="10" y="77" width="85" height="3" fill="#e5e7eb"/>' +
        '<rect x="10" y="85" width="100" height="3" fill="#e5e7eb"/>' +
        '<rect x="10" y="93" width="95" height="3" fill="#e5e7eb"/>' +
        '<rect x="10" y="130" width="35" height="3" fill="#374151"/>' +
        '<rect x="10" y="140" width="45" height="3" fill="#6b7280"/>' +
        '</svg>',
    ),
  pages: [
    {
      id: 'letterhead-classic-page-1',
      width: 216,
      height: 279,
      backgroundColor: '#FFFFFF',
      elements: [
        {
          id: 'lhc-company-name',
          type: 'text',
          x: 15,
          y: 20,
          width: 120,
          height: 12,
          rotation: 0,
          opacity: 100,
          zIndex: 0,
          locked: false,
          visible: true,
          content: 'Harrison & Associates',
          fontFamily: 'Times New Roman, serif',
          fontSize: 18,
          fontColor: '#1a2332',
          bold: true,
          italic: false,
          underline: false,
          alignment: 'left',
        },
        {
          id: 'lhc-separator',
          type: 'shape',
          x: 15,
          y: 35,
          width: 186,
          height: 1,
          rotation: 0,
          opacity: 100,
          zIndex: 1,
          locked: false,
          visible: true,
          shapeType: 'rectangle',
          fill: '#1a2332',
          stroke: '#1a2332',
          strokeWidth: 0,
          borderStyle: 'solid',
        },
        {
          id: 'lhc-contact-bar',
          type: 'text',
          x: 15,
          y: 38,
          width: 186,
          height: 8,
          rotation: 0,
          opacity: 100,
          zIndex: 2,
          locked: false,
          visible: true,
          content:
            '200 Park Avenue, 34th Floor, New York, NY 10166  |  (212) 555-0140  |  contact@harrisonlaw.com  |  www.harrisonlaw.com',
          fontFamily: 'Times New Roman, serif',
          fontSize: 9,
          fontColor: '#6b7280',
          bold: false,
          italic: false,
          underline: false,
          alignment: 'center',
        },
        {
          id: 'lhc-date',
          type: 'text',
          x: 15,
          y: 60,
          width: 80,
          height: 8,
          rotation: 0,
          opacity: 100,
          zIndex: 3,
          locked: false,
          visible: true,
          content: 'January 1, 2024',
          fontFamily: 'Times New Roman, serif',
          fontSize: 11,
          fontColor: '#374151',
          bold: false,
          italic: false,
          underline: false,
          alignment: 'left',
        },
        {
          id: 'lhc-recipient',
          type: 'text',
          x: 15,
          y: 75,
          width: 120,
          height: 25,
          rotation: 0,
          opacity: 100,
          zIndex: 4,
          locked: false,
          visible: true,
          content: 'Recipient Name\nCompany Name\n456 Business Ave\nCity, State 67890',
          fontFamily: 'Times New Roman, serif',
          fontSize: 11,
          fontColor: '#374151',
          bold: false,
          italic: false,
          underline: false,
          alignment: 'left',
        },
        {
          id: 'lhc-greeting',
          type: 'text',
          x: 15,
          y: 110,
          width: 186,
          height: 8,
          rotation: 0,
          opacity: 100,
          zIndex: 5,
          locked: false,
          visible: true,
          content: 'Dear Recipient,',
          fontFamily: 'Times New Roman, serif',
          fontSize: 11,
          fontColor: '#374151',
          bold: false,
          italic: false,
          underline: false,
          alignment: 'left',
        },
        {
          id: 'lhc-body',
          type: 'text',
          x: 15,
          y: 125,
          width: 186,
          height: 90,
          rotation: 0,
          opacity: 100,
          zIndex: 6,
          locked: false,
          visible: true,
          content:
            'I am writing to you regarding a matter of importance. Please replace this placeholder text with the body of your letter.\n\nYou may include multiple paragraphs as needed to convey your message clearly and professionally.\n\nThank you for your time and consideration. We look forward to hearing from you at your earliest convenience.',
          fontFamily: 'Times New Roman, serif',
          fontSize: 11,
          fontColor: '#374151',
          bold: false,
          italic: false,
          underline: false,
          alignment: 'left',
        },
        {
          id: 'lhc-closing',
          type: 'text',
          x: 15,
          y: 230,
          width: 80,
          height: 8,
          rotation: 0,
          opacity: 100,
          zIndex: 7,
          locked: false,
          visible: true,
          content: 'Sincerely,',
          fontFamily: 'Times New Roman, serif',
          fontSize: 11,
          fontColor: '#374151',
          bold: false,
          italic: false,
          underline: false,
          alignment: 'left',
        },
        {
          id: 'lhc-signature',
          type: 'text',
          x: 15,
          y: 250,
          width: 80,
          height: 10,
          rotation: 0,
          opacity: 100,
          zIndex: 8,
          locked: false,
          visible: true,
          content: 'Harrison & Associates',
          fontFamily: 'Times New Roman, serif',
          fontSize: 11,
          fontColor: '#1a2332',
          bold: true,
          italic: false,
          underline: false,
          alignment: 'left',
        },
      ],
    },
  ],
};

/**
 * Modern Centered Letterhead — Startup / tech company style.
 * Company name in ALL CAPS centered, tagline below, contact bar centered,
 * body text, and signature at bottom.
 */
export const letterheadModernTemplate: CanvasTemplate = {
  id: 'template-letterhead-modern',
  name: 'Modern Centered Letterhead',
  category: 'letterhead',
  thumbnail:
    'data:image/svg+xml;base64,' +
    btoa(
      '<svg width="120" height="160" xmlns="http://www.w3.org/2000/svg">' +
        '<rect width="120" height="160" fill="#fff" stroke="#e5e7eb" stroke-width="1"/>' +
        '<rect x="25" y="14" width="70" height="7" fill="#111827"/>' +
        '<rect x="35" y="25" width="50" height="3" fill="#d1d5db"/>' +
        '<rect x="20" y="33" width="80" height="3" fill="#e5e7eb"/>' +
        '<rect x="10" y="50" width="100" height="3" fill="#e5e7eb"/>' +
        '<rect x="10" y="58" width="100" height="3" fill="#e5e7eb"/>' +
        '<rect x="10" y="66" width="90" height="3" fill="#e5e7eb"/>' +
        '<rect x="10" y="74" width="100" height="3" fill="#e5e7eb"/>' +
        '<rect x="10" y="82" width="85" height="3" fill="#e5e7eb"/>' +
        '<rect x="10" y="90" width="100" height="3" fill="#e5e7eb"/>' +
        '<rect x="10" y="98" width="95" height="3" fill="#e5e7eb"/>' +
        '<rect x="10" y="130" width="35" height="3" fill="#374151"/>' +
        '<rect x="10" y="140" width="45" height="3" fill="#6b7280"/>' +
        '</svg>',
    ),
  pages: [
    {
      id: 'letterhead-modern-page-1',
      width: 216,
      height: 279,
      backgroundColor: '#FFFFFF',
      elements: [
        {
          id: 'lhm-company-name',
          type: 'text',
          x: 15,
          y: 25,
          width: 186,
          height: 14,
          rotation: 0,
          opacity: 100,
          zIndex: 0,
          locked: false,
          visible: true,
          content: 'NEXUS LABS',
          fontFamily: 'Helvetica, Arial, sans-serif',
          fontSize: 20,
          fontColor: '#111827',
          bold: true,
          italic: false,
          underline: false,
          alignment: 'center',
        },
        {
          id: 'lhm-tagline',
          type: 'text',
          x: 15,
          y: 40,
          width: 186,
          height: 8,
          rotation: 0,
          opacity: 100,
          zIndex: 1,
          locked: false,
          visible: true,
          content: 'Engineering the future, one line at a time.',
          fontFamily: 'Helvetica, Arial, sans-serif',
          fontSize: 10,
          fontColor: '#9ca3af',
          bold: false,
          italic: true,
          underline: false,
          alignment: 'center',
        },
        {
          id: 'lhm-contact-bar',
          type: 'text',
          x: 15,
          y: 50,
          width: 186,
          height: 8,
          rotation: 0,
          opacity: 100,
          zIndex: 2,
          locked: false,
          visible: true,
          content: '(415) 555-0198  •  hello@nexuslabs.io  •  nexuslabs.io',
          fontFamily: 'Helvetica, Arial, sans-serif',
          fontSize: 9,
          fontColor: '#9ca3af',
          bold: false,
          italic: false,
          underline: false,
          alignment: 'center',
        },
        {
          id: 'lhm-date',
          type: 'text',
          x: 15,
          y: 72,
          width: 80,
          height: 8,
          rotation: 0,
          opacity: 100,
          zIndex: 3,
          locked: false,
          visible: true,
          content: 'January 1, 2024',
          fontFamily: 'Helvetica, Arial, sans-serif',
          fontSize: 11,
          fontColor: '#374151',
          bold: false,
          italic: false,
          underline: false,
          alignment: 'left',
        },
        {
          id: 'lhm-recipient',
          type: 'text',
          x: 15,
          y: 87,
          width: 120,
          height: 25,
          rotation: 0,
          opacity: 100,
          zIndex: 4,
          locked: false,
          visible: true,
          content: 'Recipient Name\nCompany Name\n456 Business Ave\nCity, State 67890',
          fontFamily: 'Helvetica, Arial, sans-serif',
          fontSize: 11,
          fontColor: '#374151',
          bold: false,
          italic: false,
          underline: false,
          alignment: 'left',
        },
        {
          id: 'lhm-greeting',
          type: 'text',
          x: 15,
          y: 120,
          width: 186,
          height: 8,
          rotation: 0,
          opacity: 100,
          zIndex: 5,
          locked: false,
          visible: true,
          content: 'Dear Recipient,',
          fontFamily: 'Helvetica, Arial, sans-serif',
          fontSize: 11,
          fontColor: '#374151',
          bold: false,
          italic: false,
          underline: false,
          alignment: 'left',
        },
        {
          id: 'lhm-body',
          type: 'text',
          x: 15,
          y: 135,
          width: 186,
          height: 90,
          rotation: 0,
          opacity: 100,
          zIndex: 6,
          locked: false,
          visible: true,
          content:
            'I am writing to you regarding a matter of importance. Please replace this placeholder text with the body of your letter.\n\nYou may include multiple paragraphs as needed to convey your message clearly and professionally.\n\nThank you for your time and consideration. We look forward to hearing from you at your earliest convenience.',
          fontFamily: 'Helvetica, Arial, sans-serif',
          fontSize: 11,
          fontColor: '#374151',
          bold: false,
          italic: false,
          underline: false,
          alignment: 'left',
        },
        {
          id: 'lhm-closing',
          type: 'text',
          x: 15,
          y: 235,
          width: 80,
          height: 8,
          rotation: 0,
          opacity: 100,
          zIndex: 7,
          locked: false,
          visible: true,
          content: 'Best regards,',
          fontFamily: 'Helvetica, Arial, sans-serif',
          fontSize: 11,
          fontColor: '#374151',
          bold: false,
          italic: false,
          underline: false,
          alignment: 'left',
        },
        {
          id: 'lhm-signature',
          type: 'text',
          x: 15,
          y: 255,
          width: 80,
          height: 10,
          rotation: 0,
          opacity: 100,
          zIndex: 8,
          locked: false,
          visible: true,
          content: 'Nexus Labs',
          fontFamily: 'Helvetica, Arial, sans-serif',
          fontSize: 11,
          fontColor: '#111827',
          bold: true,
          italic: false,
          underline: false,
          alignment: 'left',
        },
      ],
    },
  ],
};

/**
 * Organization Letterhead — Non-profit / community org style.
 * 3-column header with left text, centered org name, and right text.
 * Contact bar below, separator, body text, and signature.
 */
export const letterheadOrgTemplate: CanvasTemplate = {
  id: 'template-letterhead-org',
  name: 'Organization Letterhead',
  category: 'letterhead',
  thumbnail:
    'data:image/svg+xml;base64,' +
    btoa(
      '<svg width="120" height="160" xmlns="http://www.w3.org/2000/svg">' +
        '<rect width="120" height="160" fill="#fff" stroke="#e5e7eb" stroke-width="1"/>' +
        '<rect x="10" y="12" width="25" height="5" fill="#6b7280"/>' +
        '<rect x="10" y="19" width="20" height="3" fill="#d1d5db"/>' +
        '<rect x="85" y="12" width="25" height="5" fill="#6b7280"/>' +
        '<rect x="90" y="19" width="20" height="3" fill="#d1d5db"/>' +
        '<rect x="30" y="28" width="60" height="7" fill="#1e3a5f"/>' +
        '<rect x="20" y="39" width="80" height="3" fill="#d1d5db"/>' +
        '<rect x="10" y="46" width="100" height="1" fill="#1e3a5f"/>' +
        '<rect x="10" y="56" width="100" height="3" fill="#e5e7eb"/>' +
        '<rect x="10" y="64" width="100" height="3" fill="#e5e7eb"/>' +
        '<rect x="10" y="72" width="90" height="3" fill="#e5e7eb"/>' +
        '<rect x="10" y="80" width="100" height="3" fill="#e5e7eb"/>' +
        '<rect x="10" y="88" width="85" height="3" fill="#e5e7eb"/>' +
        '<rect x="10" y="96" width="100" height="3" fill="#e5e7eb"/>' +
        '<rect x="10" y="130" width="35" height="3" fill="#374151"/>' +
        '<rect x="10" y="140" width="45" height="3" fill="#6b7280"/>' +
        '</svg>',
    ),
  pages: [
    {
      id: 'letterhead-org-page-1',
      width: 216,
      height: 279,
      backgroundColor: '#FFFFFF',
      elements: [
        {
          id: 'lho-header-left',
          type: 'text',
          x: 15,
          y: 20,
          width: 50,
          height: 14,
          rotation: 0,
          opacity: 100,
          zIndex: 0,
          locked: false,
          visible: true,
          content: 'Empowering\nCommunities',
          fontFamily: 'Helvetica, Arial, sans-serif',
          fontSize: 10,
          fontColor: '#6b7280',
          bold: false,
          italic: false,
          underline: false,
          alignment: 'left',
        },
        {
          id: 'lho-header-right',
          type: 'text',
          x: 151,
          y: 20,
          width: 50,
          height: 14,
          rotation: 0,
          opacity: 100,
          zIndex: 1,
          locked: false,
          visible: true,
          content: 'Est. 1995\nWashington, DC',
          fontFamily: 'Helvetica, Arial, sans-serif',
          fontSize: 10,
          fontColor: '#6b7280',
          bold: false,
          italic: false,
          underline: false,
          alignment: 'right',
        },
        {
          id: 'lho-company-name',
          type: 'text',
          x: 15,
          y: 38,
          width: 186,
          height: 12,
          rotation: 0,
          opacity: 100,
          zIndex: 2,
          locked: false,
          visible: true,
          content: 'Global Community Foundation',
          fontFamily: 'Helvetica, Arial, sans-serif',
          fontSize: 18,
          fontColor: '#1e3a5f',
          bold: true,
          italic: false,
          underline: false,
          alignment: 'center',
        },
        {
          id: 'lho-contact-bar',
          type: 'text',
          x: 15,
          y: 52,
          width: 186,
          height: 8,
          rotation: 0,
          opacity: 100,
          zIndex: 3,
          locked: false,
          visible: true,
          content:
            '1200 Constitution Ave NW, Washington, DC 20001  |  +1 (202) 555-0140  |  info@globalcf.org  |  www.globalcf.org',
          fontFamily: 'Helvetica, Arial, sans-serif',
          fontSize: 9,
          fontColor: '#6b7280',
          bold: false,
          italic: false,
          underline: false,
          alignment: 'center',
        },
        {
          id: 'lho-separator',
          type: 'shape',
          x: 15,
          y: 63,
          width: 186,
          height: 1,
          rotation: 0,
          opacity: 100,
          zIndex: 4,
          locked: false,
          visible: true,
          shapeType: 'rectangle',
          fill: '#1e3a5f',
          stroke: '#1e3a5f',
          strokeWidth: 0,
          borderStyle: 'solid',
        },
        {
          id: 'lho-date',
          type: 'text',
          x: 15,
          y: 75,
          width: 80,
          height: 8,
          rotation: 0,
          opacity: 100,
          zIndex: 5,
          locked: false,
          visible: true,
          content: 'January 1, 2024',
          fontFamily: 'Helvetica, Arial, sans-serif',
          fontSize: 11,
          fontColor: '#374151',
          bold: false,
          italic: false,
          underline: false,
          alignment: 'left',
        },
        {
          id: 'lho-recipient',
          type: 'text',
          x: 15,
          y: 90,
          width: 120,
          height: 25,
          rotation: 0,
          opacity: 100,
          zIndex: 6,
          locked: false,
          visible: true,
          content: 'Recipient Name\nOrganization Name\n456 Community Blvd\nCity, State 67890',
          fontFamily: 'Helvetica, Arial, sans-serif',
          fontSize: 11,
          fontColor: '#374151',
          bold: false,
          italic: false,
          underline: false,
          alignment: 'left',
        },
        {
          id: 'lho-greeting',
          type: 'text',
          x: 15,
          y: 123,
          width: 186,
          height: 8,
          rotation: 0,
          opacity: 100,
          zIndex: 7,
          locked: false,
          visible: true,
          content: 'Dear Colleague,',
          fontFamily: 'Helvetica, Arial, sans-serif',
          fontSize: 11,
          fontColor: '#374151',
          bold: false,
          italic: false,
          underline: false,
          alignment: 'left',
        },
        {
          id: 'lho-body',
          type: 'text',
          x: 15,
          y: 138,
          width: 186,
          height: 90,
          rotation: 0,
          opacity: 100,
          zIndex: 8,
          locked: false,
          visible: true,
          content:
            'On behalf of the Global Community Foundation, I am writing to you regarding a matter of shared importance. Please replace this placeholder text with the body of your letter.\n\nYou may include multiple paragraphs as needed to convey your message clearly and professionally.\n\nThank you for your continued partnership and dedication to our shared mission.',
          fontFamily: 'Helvetica, Arial, sans-serif',
          fontSize: 11,
          fontColor: '#374151',
          bold: false,
          italic: false,
          underline: false,
          alignment: 'left',
        },
        {
          id: 'lho-closing',
          type: 'text',
          x: 15,
          y: 235,
          width: 80,
          height: 8,
          rotation: 0,
          opacity: 100,
          zIndex: 9,
          locked: false,
          visible: true,
          content: 'With gratitude,',
          fontFamily: 'Helvetica, Arial, sans-serif',
          fontSize: 11,
          fontColor: '#374151',
          bold: false,
          italic: false,
          underline: false,
          alignment: 'left',
        },
        {
          id: 'lho-signature',
          type: 'text',
          x: 15,
          y: 255,
          width: 100,
          height: 10,
          rotation: 0,
          opacity: 100,
          zIndex: 10,
          locked: false,
          visible: true,
          content: 'Global Community Foundation',
          fontFamily: 'Helvetica, Arial, sans-serif',
          fontSize: 11,
          fontColor: '#1e3a5f',
          bold: true,
          italic: false,
          underline: false,
          alignment: 'left',
        },
      ],
    },
  ],
};
