import type { CanvasTemplate, TextElement, ShapeElement } from '../types';

// Presentation uses landscape A4: 297mm × 210mm
const PRESENTATION_WIDTH = 297;
const PRESENTATION_HEIGHT = 210;

const slideBackground: ShapeElement = {
  id: 'presentation-bg-accent',
  type: 'shape',
  shapeType: 'rectangle',
  x: 0,
  y: 0,
  width: PRESENTATION_WIDTH,
  height: 60,
  rotation: 0,
  opacity: 100,
  zIndex: 1,
  locked: false,
  visible: true,
  fill: '#2d3436',
  stroke: '#2d3436',
  strokeWidth: 0,
  borderStyle: 'solid',
};

const accentBar: ShapeElement = {
  id: 'presentation-accent-bar',
  type: 'shape',
  shapeType: 'rectangle',
  x: 0,
  y: 58,
  width: PRESENTATION_WIDTH,
  height: 3,
  rotation: 0,
  opacity: 100,
  zIndex: 2,
  locked: false,
  visible: true,
  fill: '#0984e3',
  stroke: '#0984e3',
  strokeWidth: 0,
  borderStyle: 'solid',
};

const slideTitle: TextElement = {
  id: 'presentation-title',
  type: 'text',
  x: 30,
  y: 12,
  width: 237,
  height: 20,
  rotation: 0,
  opacity: 100,
  zIndex: 3,
  locked: false,
  visible: true,
  content: 'Presentation Title',
  fontFamily: 'Arial',
  fontSize: 36,
  fontColor: '#FFFFFF',
  bold: true,
  italic: false,
  underline: false,
  alignment: 'left',
};

const slideSubtitle: TextElement = {
  id: 'presentation-subtitle',
  type: 'text',
  x: 30,
  y: 36,
  width: 237,
  height: 12,
  rotation: 0,
  opacity: 100,
  zIndex: 4,
  locked: false,
  visible: true,
  content: 'Subtitle or tagline goes here',
  fontFamily: 'Arial',
  fontSize: 16,
  fontColor: '#b2bec3',
  bold: false,
  italic: false,
  underline: false,
  alignment: 'left',
};

const contentArea: TextElement = {
  id: 'presentation-content',
  type: 'text',
  x: 30,
  y: 75,
  width: 237,
  height: 90,
  rotation: 0,
  opacity: 100,
  zIndex: 5,
  locked: false,
  visible: true,
  content:
    '• Key point one — describe your main idea\n\n• Key point two — supporting information\n\n• Key point three — additional details\n\n• Key point four — conclusion or call to action',
  fontFamily: 'Arial',
  fontSize: 14,
  fontColor: '#2d3436',
  bold: false,
  italic: false,
  underline: false,
  alignment: 'left',
};

const footerLine: ShapeElement = {
  id: 'presentation-footer-line',
  type: 'shape',
  shapeType: 'line',
  x: 30,
  y: 185,
  width: 237,
  height: 0.5,
  rotation: 0,
  opacity: 100,
  zIndex: 6,
  locked: false,
  visible: true,
  fill: 'transparent',
  stroke: '#dfe6e9',
  strokeWidth: 1,
  borderStyle: 'solid',
};

const footerText: TextElement = {
  id: 'presentation-footer-text',
  type: 'text',
  x: 30,
  y: 190,
  width: 120,
  height: 7,
  rotation: 0,
  opacity: 100,
  zIndex: 7,
  locked: false,
  visible: true,
  content: 'Your Name | Company',
  fontFamily: 'Arial',
  fontSize: 9,
  fontColor: '#636e72',
  bold: false,
  italic: false,
  underline: false,
  alignment: 'left',
};

const pageNumber: TextElement = {
  id: 'presentation-page-number',
  type: 'text',
  x: 250,
  y: 190,
  width: 20,
  height: 7,
  rotation: 0,
  opacity: 100,
  zIndex: 8,
  locked: false,
  visible: true,
  content: '1',
  fontFamily: 'Arial',
  fontSize: 9,
  fontColor: '#636e72',
  bold: false,
  italic: false,
  underline: false,
  alignment: 'right',
};

export const presentationTemplate: CanvasTemplate = {
  id: 'presentation-slide',
  name: 'Presentation Slide',
  category: 'presentation',
  thumbnail:
    'data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMTYwIiBoZWlnaHQ9IjEyMCIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cmVjdCB3aWR0aD0iMTYwIiBoZWlnaHQ9IjEyMCIgZmlsbD0iI2ZmZiIgc3Ryb2tlPSIjZTBlMGUwIiBzdHJva2Utd2lkdGg9IjEiLz48cmVjdCB4PSIwIiB5PSIwIiB3aWR0aD0iMTYwIiBoZWlnaHQ9IjM1IiBmaWxsPSIjMmQzNDM2Ii8+PHJlY3QgeD0iMCIgeT0iMzQiIHdpZHRoPSIxNjAiIGhlaWdodD0iMiIgZmlsbD0iIzA5ODRlMyIvPjx0ZXh0IHg9IjE1IiB5PSIxOCIgZm9udC1zaXplPSIxMCIgZm9udC13ZWlnaHQ9ImJvbGQiIGZpbGw9IiNmZmYiPlByZXNlbnRhdGlvbjwvdGV4dD48dGV4dCB4PSIxNSIgeT0iMjgiIGZvbnQtc2l6ZT0iNiIgZmlsbD0iI2IyYmVjMyI+U3VidGl0bGU8L3RleHQ+PHJlY3QgeD0iMTUiIHk9IjQ1IiB3aWR0aD0iMTAwIiBoZWlnaHQ9IjMiIGZpbGw9IiNlMGUwZTAiLz48cmVjdCB4PSIxNSIgeT0iNTIiIHdpZHRoPSIxMTAiIGhlaWdodD0iMyIgZmlsbD0iI2UwZTBlMCIvPjxyZWN0IHg9IjE1IiB5PSI1OSIgd2lkdGg9IjkwIiBoZWlnaHQ9IjMiIGZpbGw9IiNlMGUwZTAiLz48cmVjdCB4PSIxNSIgeT0iNjYiIHdpZHRoPSIxMDUiIGhlaWdodD0iMyIgZmlsbD0iI2UwZTBlMCIvPjxsaW5lIHgxPSIxNSIgeTE9IjEwNSIgeDI9IjE0NSIgeTI9IjEwNSIgc3Ryb2tlPSIjZGZlNmU5IiBzdHJva2Utd2lkdGg9IjEiLz48L3N2Zz4=',
  pages: [
    {
      id: 'presentation-page-1',
      width: PRESENTATION_WIDTH,
      height: PRESENTATION_HEIGHT,
      backgroundColor: '#FFFFFF',
      elements: [
        slideBackground,
        accentBar,
        slideTitle,
        slideSubtitle,
        contentArea,
        footerLine,
        footerText,
        pageNumber,
      ],
    },
  ],
};
