/**
 * Design Token Generator
 *
 * Reads the design tokens from `src/design-system/tokens.ts` and generates:
 * 1. `src/design-system/tokens.generated.css` — CSS custom properties for all tokens
 * 2. Updates `tailwind.config.ts` theme extension to reference CSS custom properties
 *
 * Usage: npx tsx scripts/generate-tokens.ts
 */

import { writeFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const ROOT = resolve(__dirname, '..');

// Import tokens directly
import { tokens } from '../src/design-system/tokens.js';

// ---------------------------------------------------------------------------
// CSS Custom Properties Generation
// ---------------------------------------------------------------------------

function generateColorVars(scale: Record<number | string, string>, prefix: string): string[] {
  return Object.entries(scale).map(([key, value]) => `  --color-${prefix}-${key}: ${value};`);
}

function generateCSSCustomProperties(): string {
  const lines: string[] = [];

  lines.push('/* Auto-generated by scripts/generate-tokens.ts — DO NOT EDIT */');
  lines.push('');
  lines.push(':root {');

  // Colors — scales
  const colorScales = ['primary', 'secondary', 'accent', 'success', 'error'] as const;
  for (const scale of colorScales) {
    lines.push(`  /* ${scale} */`);
    lines.push(...generateColorVars(tokens.colors[scale], scale));
  }

  // Colors — semantic (light theme defaults)
  lines.push('');
  lines.push('  /* semantic colors (light theme) */');
  lines.push(`  --color-background: ${tokens.colors.background.light};`);
  lines.push(`  --color-text: ${tokens.colors.text.light};`);
  lines.push(`  --color-text-muted: ${tokens.colors.text.muted};`);

  // Spacing
  lines.push('');
  lines.push('  /* spacing */');
  for (const [key, value] of Object.entries(tokens.spacing)) {
    const remValue = value === 0 ? '0px' : `${value / 16}rem`;
    lines.push(`  --spacing-${key}: ${remValue};`);
  }

  // Typography
  lines.push('');
  lines.push('  /* typography */');
  lines.push(`  --font-sans: ${tokens.typography.fontFamily.sans.join(', ')};`);
  lines.push(`  --font-mono: ${tokens.typography.fontFamily.mono.join(', ')};`);

  for (const [key, [size, { lineHeight }]] of Object.entries(tokens.typography.fontSize)) {
    lines.push(`  --font-size-${key}: ${size};`);
    lines.push(`  --line-height-${key}: ${lineHeight};`);
  }

  for (const [key, value] of Object.entries(tokens.typography.fontWeight)) {
    lines.push(`  --font-weight-${key}: ${value};`);
  }

  // Border Radius
  lines.push('');
  lines.push('  /* border-radius */');
  for (const [key, value] of Object.entries(tokens.borderRadius)) {
    lines.push(`  --radius-${key}: ${value};`);
  }

  // Shadows
  lines.push('');
  lines.push('  /* shadows */');
  for (const [key, value] of Object.entries(tokens.shadows)) {
    lines.push(`  --shadow-${key}: ${value};`);
  }

  // Border Width
  lines.push('');
  lines.push('  /* border-width */');
  for (const [key, value] of Object.entries(tokens.borderWidth)) {
    lines.push(`  --border-${key}: ${value};`);
  }

  // Motion
  lines.push('');
  lines.push('  /* motion — durations */');
  for (const [key, value] of Object.entries(tokens.motion.duration)) {
    lines.push(`  --duration-${key}: ${value};`);
  }

  lines.push('');
  lines.push('  /* motion — easing */');
  for (const [key, value] of Object.entries(tokens.motion.easing)) {
    lines.push(`  --${key}: ${value};`);
  }

  lines.push('}');

  // Dark theme overrides
  lines.push('');
  lines.push('.dark, [data-theme="dark"] {');
  lines.push(`  --color-background: ${tokens.colors.background.dark};`);
  lines.push(`  --color-text: ${tokens.colors.text.dark};`);
  lines.push(`  --color-text-muted: ${tokens.colors.text.muted};`);
  lines.push('}');
  lines.push('');

  return lines.join('\n');
}

// ---------------------------------------------------------------------------
// Tailwind Config Generation
// ---------------------------------------------------------------------------

function generateTailwindConfig(): string {
  // Build color objects that reference CSS custom properties
  const colorScales = ['primary', 'secondary', 'accent', 'success', 'error'] as const;

  const colorEntries: string[] = [];
  for (const scale of colorScales) {
    const shades = Object.keys(tokens.colors[scale]);
    const shadeEntries = shades
      .map((shade) => `          ${shade}: 'var(--color-${scale}-${shade})',`)
      .join('\n');
    colorEntries.push(
      `        ${scale}: {\n${shadeEntries}\n          DEFAULT: 'var(--color-${scale}-500)',\n        },`,
    );
  }

  // Semantic colors
  colorEntries.push(`        background: {
          light: 'var(--color-background)',
          dark: 'var(--color-background)',
          DEFAULT: 'var(--color-background)',
        },`);
  colorEntries.push(`        text: {
          light: 'var(--color-text)',
          muted: 'var(--color-text-muted)',
          dark: 'var(--color-text)',
          DEFAULT: 'var(--color-text)',
        },`);

  // Spacing
  const spacingEntries = Object.entries(tokens.spacing)
    .map(([key, value]) => {
      const remValue = value === 0 ? '0px' : `${value / 16}rem`;
      return `        '${key}': 'var(--spacing-${key}, ${remValue})',`;
    })
    .join('\n');

  // Font family
  const fontSansStr = tokens.typography.fontFamily.sans.map((f) => `'${f}'`).join(', ');
  const fontMonoStr = tokens.typography.fontFamily.mono.map((f) => `'${f}'`).join(', ');

  // Font size
  const fontSizeEntries = Object.entries(tokens.typography.fontSize)
    .map(([key, [size, { lineHeight }]]) => {
      return `        '${key}': ['var(--font-size-${key}, ${size})', { lineHeight: 'var(--line-height-${key}, ${lineHeight})' }],`;
    })
    .join('\n');

  // Border radius
  const borderRadiusEntries = Object.entries(tokens.borderRadius)
    .map(([key, value]) => `        ${key}: 'var(--radius-${key}, ${value})',`)
    .join('\n');

  // Shadows
  const shadowEntries = Object.entries(tokens.shadows)
    .map(([key, value]) => {
      const escapedValue = value === 'none' ? 'none' : `var(--shadow-${key})`;
      return `        '${key}': '${escapedValue}',`;
    })
    .join('\n');

  // Border width
  const borderWidthEntries = Object.entries(tokens.borderWidth)
    .map(([key, value]) => `        ${key}: 'var(--border-${key}, ${value})',`)
    .join('\n');

  // Transition duration
  const durationEntries = Object.entries(tokens.motion.duration)
    .map(([key, value]) => `        ${key}: 'var(--duration-${key}, ${value})',`)
    .join('\n');

  // Transition timing function
  const easingEntries = Object.entries(tokens.motion.easing)
    .map(([key, value]) => `        '${key}': 'var(--${key}, ${value})',`)
    .join('\n');

  const config = `import type { Config } from 'tailwindcss';

/**
 * Tailwind CSS Configuration
 *
 * Theme values are generated from design tokens (src/design-system/tokens.ts).
 * Run \`npm run generate:tokens\` to regenerate after token changes.
 */
const config: Config = {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
${colorEntries.join('\n')}
      },
      spacing: {
${spacingEntries}
      },
      fontFamily: {
        sans: [${fontSansStr}],
        mono: [${fontMonoStr}],
      },
      fontSize: {
${fontSizeEntries}
      },
      borderRadius: {
${borderRadiusEntries}
      },
      boxShadow: {
${shadowEntries}
      },
      borderWidth: {
${borderWidthEntries}
      },
      transitionDuration: {
${durationEntries}
      },
      transitionTimingFunction: {
${easingEntries}
      },
      screens: {
        sm: '640px',
        md: '768px',
        lg: '1024px',
        xl: '1280px',
      },
      keyframes: {
        indeterminate: {
          '0%': { transform: 'translateX(-100%)' },
          '100%': { transform: 'translateX(400%)' },
        },
        'slide-up': {
          '0%': { transform: 'translateY(100%)' },
          '100%': { transform: 'translateY(0)' },
        },
      },
      animation: {
        indeterminate: 'indeterminate 1.5s ease-in-out infinite',
        'slide-up': 'slide-up 200ms ease',
      },
    },
  },
  plugins: [],
};

export default config;
`;

  return config;
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

function main(): void {
  // eslint-disable-next-line no-console
  console.log('🎨 Generating design tokens...\n');

  // 1. Generate CSS custom properties
  const cssContent = generateCSSCustomProperties();
  const cssPath = resolve(ROOT, 'src/design-system/tokens.generated.css');
  writeFileSync(cssPath, cssContent, 'utf-8');
  // eslint-disable-next-line no-console
  console.log(`  ✓ Generated ${cssPath}`);

  // 2. Generate Tailwind config
  const tailwindContent = generateTailwindConfig();
  const tailwindPath = resolve(ROOT, 'tailwind.config.ts');
  writeFileSync(tailwindPath, tailwindContent, 'utf-8');
  // eslint-disable-next-line no-console
  console.log(`  ✓ Updated ${tailwindPath}`);

  // eslint-disable-next-line no-console
  console.log('\n✅ Token generation complete!');
}

main();
